import Head from 'next/head'
import { Karla } from 'next/font/google'
import Header from "./Header"
import Middle from "./Middle"
import Footer from "./Footer"
import Home from "./Home"
const karla = Karla({ subsets: ['latin'] })

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon-32x32.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&display=swap" rel="stylesheet" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Karla:wght@400;700&display=swap" rel="stylesheet" />
      </Head>
      <Header />
      <main>
        <Home />
        <Middle />
      </main>
      <Footer />
    </>
  )
}
